### PR TITLE
Monitor external package now returns response

### PR DESCRIPTION
**Pull request by mrmarkfrench**
monitor_external() now returns the response from the remote, rather than simply TRUE. This response contains helpful information, including the current status of the requested package and an estimated delivery date.

### CODE REVIEW

**Comment by tmodrzynski** [comment]
Thanks!

**Comment by mrmarkfrench** [comment]
My pleasure. Any idea when you expect this change to be rolled out to Packagist?

**Comment by tmodrzynski** [comment]
It has already been pulled by them, and this change should be available in version 1.3.2.

**Comment by mrmarkfrench** [comment]
I see a new version was published to Packagist yesterday. Thanks for your quick turn-around on this.

**Comment by tmodrzynski** [comment]
No problem!

**Pull request merged**
